#!/usr/bin/env bash
set -euo pipefail

# Evo-RL closer setting for DexJoCo click_mouse:
# - collect an initial baseline data pool D0,
# - keep both successful and failed episodes,
# - append each new rollout batch to the data pool,
# - run three policy-improvement rounds and evaluate the final policy.
export DEXJOCO_EVO_MERGE_POOL="${DEXJOCO_EVO_MERGE_POOL:-1}"
export DEXJOCO_EVO_INITIAL_COLLECT_EPISODES="${DEXJOCO_EVO_INITIAL_COLLECT_EPISODES:-500}"
export DEXJOCO_EVO_ROUNDS="${DEXJOCO_EVO_ROUNDS:-3}"
export DEXJOCO_EVO_COLLECT_EPISODES="${DEXJOCO_EVO_COLLECT_EPISODES:-120}"
export DEXJOCO_EVO_TRAIN_STEPS="${DEXJOCO_EVO_TRAIN_STEPS:-1200}"
export DEXJOCO_EVAL_EPISODES="${DEXJOCO_EVAL_EPISODES:-100}"

export DEXJOCO_RECAP_INCLUDE_FAILURES="${DEXJOCO_RECAP_INCLUDE_FAILURES:-1}"
export DEXJOCO_RECAP_LABEL_WITH_VALUE="${DEXJOCO_RECAP_LABEL_WITH_VALUE:-1}"
export DEXJOCO_RECAP_VALUE_POSITIVE_SUCCESS_ONLY="${DEXJOCO_RECAP_VALUE_POSITIVE_SUCCESS_ONLY:-0}"
export DEXJOCO_RECAP_VALUE_EXACT_TOP_K="${DEXJOCO_RECAP_VALUE_EXACT_TOP_K:-1}"
export DEXJOCO_RECAP_VALUE_POSITIVE_RATIO="${DEXJOCO_RECAP_VALUE_POSITIVE_RATIO:-0.2}"
export DEXJOCO_RECAP_VALUE_C_FAIL_COEF="${DEXJOCO_RECAP_VALUE_C_FAIL_COEF:-1.0}"

export OPENPI_RECAP_BASE_REPEAT="${OPENPI_RECAP_BASE_REPEAT:-0}"
export OPENPI_RECAP_POSITIVE_REPEAT="${OPENPI_RECAP_POSITIVE_REPEAT:-5}"
export OPENPI_RECAP_INDICATOR_FIELD="${OPENPI_RECAP_INDICATOR_FIELD:-acp_indicator}"

exec bash jobs/37_dexjoco_click_mouse_evorl_multiround.sh
