#!/usr/bin/env bash
set -euo pipefail

# Faithful DexJoCo ReCap path:
# - collect base-prompt pi0.5 rollouts,
# - keep successful and failed episodes,
# - convert compact rollout NPZ to LeRobot,
# - train Evo-RL pistar06 value model,
# - run Evo-RL value inference for advantage/ACP indicators,
# - fine-tune OpenPI with indicator-conditioned ACP prompts,
# - evaluate under the ACP prompt.
export DEXJOCO_COLLECT_EPISODES="${DEXJOCO_COLLECT_EPISODES:-240}"
export DEXJOCO_EVAL_EPISODES="${DEXJOCO_EVAL_EPISODES:-100}"
export DEXJOCO_RECAP_INCLUDE_FAILURES="${DEXJOCO_RECAP_INCLUDE_FAILURES:-1}"
export DEXJOCO_RECAP_COLLECT_PROMPT_MODE="${DEXJOCO_RECAP_COLLECT_PROMPT_MODE:-base}"
export DEXJOCO_RECAP_LABEL_WITH_VALUE="${DEXJOCO_RECAP_LABEL_WITH_VALUE:-1}"
export DEXJOCO_RECAP_LABEL_BACKEND="${DEXJOCO_RECAP_LABEL_BACKEND:-pistar06}"

export DEXJOCO_RECAP_VALUE_N_STEP="${DEXJOCO_RECAP_VALUE_N_STEP:-50}"
export DEXJOCO_RECAP_VALUE_POSITIVE_RATIO="${DEXJOCO_RECAP_VALUE_POSITIVE_RATIO:-0.2}"
export DEXJOCO_RECAP_VALUE_C_FAIL_COEF="${DEXJOCO_RECAP_VALUE_C_FAIL_COEF:-1.0}"
export DEXJOCO_RECAP_POOL_MAX_FRAMES="${DEXJOCO_RECAP_POOL_MAX_FRAMES:-0}"
export DEXJOCO_RECAP_POOL_MAX_EPISODES="${DEXJOCO_RECAP_POOL_MAX_EPISODES:-0}"

export DEXJOCO_RECAP_PISTAR06_VALUE_STEPS="${DEXJOCO_RECAP_PISTAR06_VALUE_STEPS:-8000}"
export DEXJOCO_RECAP_PISTAR06_VALUE_BATCH_SIZE="${DEXJOCO_RECAP_PISTAR06_VALUE_BATCH_SIZE:-16}"
export DEXJOCO_RECAP_PISTAR06_VALUE_NUM_WORKERS="${DEXJOCO_RECAP_PISTAR06_VALUE_NUM_WORKERS:-2}"

export OPENPI_RECAP_PROMPT_MODE="${OPENPI_RECAP_PROMPT_MODE:-indicator}"
export OPENPI_RECAP_BASE_REPEAT="${OPENPI_RECAP_BASE_REPEAT:-0}"
export OPENPI_RECAP_POSITIVE_REPEAT="${OPENPI_RECAP_POSITIVE_REPEAT:-5}"
export OPENPI_RECAP_INDICATOR_FIELD="${OPENPI_RECAP_INDICATOR_FIELD:-acp_indicator}"

export DEXJOCO_RECAP_EVAL_PROMPT_MODE="${DEXJOCO_RECAP_EVAL_PROMPT_MODE:-acp}"
export DEXJOCO_RECAP_TRAIN_STEPS="${DEXJOCO_RECAP_TRAIN_STEPS:-2000}"
export DEXJOCO_RECAP_FSDP_DEVICES="${DEXJOCO_RECAP_FSDP_DEVICES:-1}"
export DEXJOCO_RECAP_NUM_WORKERS="${DEXJOCO_RECAP_NUM_WORKERS:-0}"
export DEXJOCO_RECAP_WARMUP_STEPS="${DEXJOCO_RECAP_WARMUP_STEPS:-150}"
export DEXJOCO_RECAP_SAVE_INTERVAL="${DEXJOCO_RECAP_SAVE_INTERVAL:-500}"
export DEXJOCO_RECAP_EXP_NAME="${DEXJOCO_RECAP_EXP_NAME:-recap_pistar06_full_eval100}"

exec bash jobs/25_dexjoco_click_mouse_recap_rollout_finetune.sh
