#!/usr/bin/env bash
set -euo pipefail

# Control: LoRA fine-tune on the collected full rollout data with the original
# base prompt only. This estimates the effect of extra BC/LoRA data without ACP
# prompt conditioning or value/advantage selection.
export DEXJOCO_COLLECT_EPISODES="${DEXJOCO_COLLECT_EPISODES:-240}"
export DEXJOCO_EVAL_EPISODES="${DEXJOCO_EVAL_EPISODES:-100}"
export DEXJOCO_RECAP_INCLUDE_FAILURES="${DEXJOCO_RECAP_INCLUDE_FAILURES:-1}"
export DEXJOCO_RECAP_COLLECT_PROMPT_MODE="${DEXJOCO_RECAP_COLLECT_PROMPT_MODE:-base}"
export DEXJOCO_RECAP_LABEL_WITH_VALUE="${DEXJOCO_RECAP_LABEL_WITH_VALUE:-0}"
export DEXJOCO_RECAP_LABEL_BACKEND="${DEXJOCO_RECAP_LABEL_BACKEND:-none}"

export OPENPI_RECAP_PROMPT_MODE="${OPENPI_RECAP_PROMPT_MODE:-base}"
export OPENPI_RECAP_BASE_REPEAT="${OPENPI_RECAP_BASE_REPEAT:-0}"
export OPENPI_RECAP_POSITIVE_REPEAT="${OPENPI_RECAP_POSITIVE_REPEAT:-1}"

export DEXJOCO_RECAP_EVAL_PROMPT_MODE="${DEXJOCO_RECAP_EVAL_PROMPT_MODE:-base}"
export DEXJOCO_RECAP_TRAIN_STEPS="${DEXJOCO_RECAP_TRAIN_STEPS:-2000}"
export DEXJOCO_RECAP_FSDP_DEVICES="${DEXJOCO_RECAP_FSDP_DEVICES:-1}"
export DEXJOCO_RECAP_NUM_WORKERS="${DEXJOCO_RECAP_NUM_WORKERS:-0}"
export DEXJOCO_RECAP_WARMUP_STEPS="${DEXJOCO_RECAP_WARMUP_STEPS:-150}"
export DEXJOCO_RECAP_SAVE_INTERVAL="${DEXJOCO_RECAP_SAVE_INTERVAL:-500}"
export DEXJOCO_RECAP_EXP_NAME="${DEXJOCO_RECAP_EXP_NAME:-base_lora_full_eval100}"

exec bash jobs/25_dexjoco_click_mouse_recap_rollout_finetune.sh
